---

version: '3'

tasks:
  build:
    cmds:
      - docker build . -t devops-book -f dev.Dockerfile

  run:
    deps:
      - clean
      - build
    cmds:
      - docker run --name devops-book --detach --volume $(pwd):/work --publish 8080:8080 devops-book
      - xdg-open http://127.0.0.1:8080

  stop:
    cmds:
      - docker stop devops-book || true

  clean:
    deps:
      - stop
    cmds:
      - docker rm devops-book || true
